package week3Prac;

/**
 * This program demonstrates a solution to the Rodents of Unusual Size question.
 * The code was generated by ChatGPT
 * Modified by Paul Davies, SC COMP2015
 */

import java.util.Scanner;

public class RodentsOfUnusualSize {

public static void main(String[] args) {
Scanner kb = new Scanner(System.in);

int num1, num;
double num2;


do {System.out.print("Enter initial population of Rodents of Unusual Size (minimum 300): ");
num1 = kb.nextInt();
System.out.print("Enter average annual population increase (as a percentage, must be >= 0): ");
num2 = kb.nextDouble();
System.out.print("Enter number of years to estimate population (minimum 10): ");
num = kb.nextInt();
} while (num1 < 300 || num2 < 0 || num < 10);
System.out.println("\nPopulation growth prediction:\n");
for (int i = 1; i < num; i++) {
System.out.printf("Year %d: Population = %d\n", i, num1);
num1 = (int) (num1 * num2 / 100);
}}}
